package tools

const (
	MaintenanceHourField           = "maintenance_hour"
	AppField                       = "app"
	DockerVolumeField              = "docker_volume"
	BackupIdField                  = "backup_id"
	OperationField                 = "operation"
	OngoingOperationField          = "ongoing_operation"
	AttemptedOperationField        = "attempted_operation"
	UrlPathField                   = "url_path"
	VersionIdField                 = "version_id"
	MaintainerField                = "maintainer"
	RequestHostField               = "request_host"
	BaseDomainField                = "base_domain"
	PortField                      = "port"
	UrlField                       = "url"
	VersionZipPathField            = "version_zip_path"
	RoleField                      = "role"
	UserField                      = "user"
	ConfigKeyField                 = "config_key"
	AppIdField                     = "app_id"
	CommandField                   = "command"
	CommandArgsField               = "command_args"
	IsRequestAddressedToAnAppField = "is_request_addressed_to_an_app"
	BackupNumberField              = "backup_number"
	IsLocalBackupField             = "is_local_backup"
	SourcePathField                = "source_path"
	DestinationPathField           = "destination_path"
	RequestOriginHostField         = "request_origin_host"
	ActualNumberField              = "actual_number"
)
